name: Scraper Unit
on:
  workflow_dispatch:
  schedule:
    - cron: "30 12 * * 6"

jobs:
  scrape:
    runs-on: ubuntu-latest
    name: Mengambil data dan screenshot

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Enable corepack
        run: corepack enable

      - name: PNPM install
        run: pnpm install

      - name: Run scraping unit
        run: pnpm start

      - name: Push new result to result folder
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          TIMESTAMP=$(date +"%Y-%m-%dT%H:%M:%S%z")

          git add result; git commit -m "[IMAGE and/or DATA FETCHED] $TIMESTAMP"
          git push
