name: Scraper Unit
on: [workflow_dispatch]

jobs:
  scrape:
    runs-on: ubuntu-latest
    name: Mengambil data dan screenshot

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: PNPM install
        uses: ./.github/actions/pnpm-install

      - name: Run scraping unit
        run: pnpm scrape

      - name: push changes to remote
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          TIMESTAMP=$(date +"%Y-%m-%dT%H:%M:%S%z")

          git add result; git commit -m "[IMAGE FETCH] $TIMESTAMP"
          git push
